import type { DomainConfig, DomainScenarios } from '@/types';

export const environmentConfig: DomainConfig = {
  id: 'environment',
  label: 'Environment',
  color: '#10b981',
  parameters: [
    {
      id: 'aqi',
      label: 'AQI',
      unit: 'AQI',
      min: 0,
      max: 500,
      ideal: 15,
      safeMin: 0,
      safeMax: 100,
      critMax: 200,
      weight: 2.0,
    },
    {
      id: 'pm25',
      label: 'PM2.5',
      unit: 'μg/m³',
      min: 0,
      max: 300,
      ideal: 5,
      safeMin: 0,
      safeMax: 35,
      critMax: 150,
      weight: 2.3,
    },
    {
      id: 'temperature',
      label: 'Temperature',
      unit: '°C',
      min: -10,
      max: 55,
      ideal: 22,
      safeMin: 10,
      safeMax: 35,
      critMin: -5,
      critMax: 45,
      weight: 1.2,
    },
    {
      id: 'humidity',
      label: 'Humidity',
      unit: '%',
      min: 0,
      max: 100,
      ideal: 50,
      safeMin: 30,
      safeMax: 70,
      critMin: 10,
      critMax: 90,
      weight: 1.0,
    },
    {
      id: 'co2',
      label: 'CO₂',
      unit: 'ppm',
      min: 300,
      max: 5000,
      ideal: 420,
      safeMin: 300,
      safeMax: 1000,
      critMax: 2500,
      weight: 1.7,
    },
    {
      id: 'noise',
      label: 'Noise',
      unit: 'dB',
      min: 20,
      max: 120,
      ideal: 40,
      safeMin: 25,
      safeMax: 65,
      critMax: 85,
      weight: 1.4,
    },
  ],
};

export const environmentScenarios: DomainScenarios = {
  normal: {
    aqi: 35,
    pm25: 12,
    temperature: 23,
    humidity: 55,
    co2: 450,
    noise: 42,
  },
  alert: {
    aqi: 120,
    pm25: 55,
    temperature: 38,
    humidity: 78,
    co2: 1400,
    noise: 72,
  },
  critical: {
    aqi: 180,
    pm25: 120,
    temperature: 43,
    humidity: 88,
    co2: 2200,
    noise: 82,
  },
};
