import type { DomainConfig, DomainScenarios } from '@/types';

export const infrastructureConfig: DomainConfig = {
  id: 'infrastructure',
  label: 'Infrastructure',
  color: '#f59e0b',
  parameters: [
    {
      id: 'loadStress',
      label: 'Load Stress',
      unit: '%',
      min: 0,
      max: 100,
      ideal: 20,
      safeMin: 0,
      safeMax: 60,
      critMax: 85,
      weight: 2.2,
    },
    {
      id: 'vibration',
      label: 'Vibration',
      unit: 'Hz',
      min: 0,
      max: 100,
      ideal: 5,
      safeMin: 0,
      safeMax: 25,
      critMax: 60,
      weight: 1.9,
    },
    {
      id: 'crackIndex',
      label: 'Crack Index',
      unit: 'CI',
      min: 0,
      max: 1,
      ideal: 0,
      safeMin: 0,
      safeMax: 0.3,
      critMax: 0.7,
      weight: 2.5,
    },
    {
      id: 'temperature',
      label: 'Temperature',
      unit: '°C',
      min: -20,
      max: 80,
      ideal: 20,
      safeMin: -5,
      safeMax: 45,
      critMin: -15,
      critMax: 65,
      weight: 1.3,
    },
    {
      id: 'moisture',
      label: 'Moisture',
      unit: '%',
      min: 0,
      max: 100,
      ideal: 15,
      safeMin: 5,
      safeMax: 40,
      critMax: 75,
      weight: 1.6,
    },
    {
      id: 'usageIntensity',
      label: 'Usage Intensity',
      unit: '%',
      min: 0,
      max: 100,
      ideal: 40,
      safeMin: 10,
      safeMax: 75,
      critMax: 92,
      weight: 1.4,
    },
  ],
};

export const infrastructureScenarios: DomainScenarios = {
  normal: {
    loadStress: 25,
    vibration: 8,
    crackIndex: 0.1,
    temperature: 22,
    moisture: 18,
    usageIntensity: 45,
  },
  alert: {
    loadStress: 55,
    vibration: 35,
    crackIndex: 0.4,
    temperature: 50,
    moisture: 55,
    usageIntensity: 78,
  },
  critical: {
    loadStress: 80,
    vibration: 55,
    crackIndex: 0.65,
    temperature: 62,
    moisture: 70,
    usageIntensity: 90,
  },
};
