import type { DomainConfig, DomainScenarios } from '@/types';

export const waterConfig: DomainConfig = {
  id: 'water',
  label: 'Water',
  color: '#0ea5e9',
  parameters: [
    {
      id: 'ph',
      label: 'pH',
      unit: '',
      min: 0,
      max: 14,
      ideal: 7,
      safeMin: 6.5,
      safeMax: 8.5,
      critMin: 4,
      critMax: 11,
      weight: 2.0,
    },
    {
      id: 'turbidity',
      label: 'Turbidity',
      unit: 'NTU',
      min: 0,
      max: 100,
      ideal: 0.5,
      safeMin: 0,
      safeMax: 4,
      critMax: 15,
      weight: 1.8,
    },
    {
      id: 'dissolvedOxygen',
      label: 'Dissolved Oxygen',
      unit: 'mg/L',
      min: 0,
      max: 20,
      ideal: 9,
      safeMin: 7,
      safeMax: 14,
      critMin: 3,
      weight: 1.5,
    },
    {
      id: 'conductivity',
      label: 'Conductivity',
      unit: 'μS/cm',
      min: 0,
      max: 2000,
      ideal: 300,
      safeMin: 100,
      safeMax: 800,
      critMax: 1500,
      weight: 1.2,
    },
    {
      id: 'temperature',
      label: 'Temperature',
      unit: '°C',
      min: 0,
      max: 45,
      ideal: 20,
      safeMin: 10,
      safeMax: 30,
      critMax: 40,
      weight: 1.0,
    },
    {
      id: 'nitrate',
      label: 'Nitrate',
      unit: 'mg/L',
      min: 0,
      max: 100,
      ideal: 2,
      safeMin: 0,
      safeMax: 10,
      critMax: 50,
      weight: 1.6,
    },
  ],
};

export const waterScenarios: DomainScenarios = {
  normal: {
    ph: 7.2,
    turbidity: 1.5,
    dissolvedOxygen: 8.5,
    conductivity: 350,
    temperature: 18,
    nitrate: 3,
  },
  alert: {
    ph: 5.8,
    turbidity: 8,
    dissolvedOxygen: 5.5,
    conductivity: 950,
    temperature: 32,
    nitrate: 25,
  },
  critical: {
    ph: 4.5,
    turbidity: 12,
    dissolvedOxygen: 3.5,
    conductivity: 1400,
    temperature: 38,
    nitrate: 45,
  },
};
